VOCS\PlatformBundle\Entity\Schools:
    exclusion_policy: none
    properties:
        id:
            groups: ['school', 'classe']
        nom:
            groups: ['school', 'classe']
        cp:
            groups: ['school']